#include "stop_1l_babyAnalyzer.h"
stop_1l_babyAnalyzer babyAnalyzer;
namespace stop_1l {
	const unsigned int &run() { return babyAnalyzer.run(); }
	const unsigned int &ls() { return babyAnalyzer.ls(); }
	const unsigned int &evt() { return babyAnalyzer.evt(); }
	const int &nvtxs() { return babyAnalyzer.nvtxs(); }
	const int &firstGoodVtxIdx() { return babyAnalyzer.firstGoodVtxIdx(); }
	const int &firstVtx_isfake() { return babyAnalyzer.firstVtx_isfake(); }
	const float &firstVtx_ndof() { return babyAnalyzer.firstVtx_ndof(); }
	const float &firstVtx_posRho() { return babyAnalyzer.firstVtx_posRho(); }
	const float &firstVtx_posZ() { return babyAnalyzer.firstVtx_posZ(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &firstVtx_posp4() { return babyAnalyzer.firstVtx_posp4(); }
	const int &pu_nvtxs() { return babyAnalyzer.pu_nvtxs(); }
	const float &pfmet() { return babyAnalyzer.pfmet(); }
	const float &pfmet_phi() { return babyAnalyzer.pfmet_phi(); }
	const float &calomet() { return babyAnalyzer.calomet(); }
	const float &calomet_phi() { return babyAnalyzer.calomet_phi(); }
	const float &filt_cscbeamhalo() { return babyAnalyzer.filt_cscbeamhalo(); }
	const float &filt_ecallaser() { return babyAnalyzer.filt_ecallaser(); }
	const float &filt_ecaltp() { return babyAnalyzer.filt_ecaltp(); }
	const float &filt_eebadsc() { return babyAnalyzer.filt_eebadsc(); }
	const float &filt_goodvtx() { return babyAnalyzer.filt_goodvtx(); }
	const float &filt_badevents() { return babyAnalyzer.filt_badevents(); }
	const float &filt_hbhenoise() { return babyAnalyzer.filt_hbhenoise(); }
	const float &filt_hcallaser() { return babyAnalyzer.filt_hcallaser(); }
	const float &filt_met() { return babyAnalyzer.filt_met(); }
	const float &filt_trkfail() { return babyAnalyzer.filt_trkfail(); }
	const float &filt_trkPOG() { return babyAnalyzer.filt_trkPOG(); }
	const float &filt_trkPOG_tmc() { return babyAnalyzer.filt_trkPOG_tmc(); }
	const float &filt_trkPOG_tms() { return babyAnalyzer.filt_trkPOG_tms(); }
	const float &filt_eff() { return babyAnalyzer.filt_eff(); }
	const float &scale1fb() { return babyAnalyzer.scale1fb(); }
	const float &xsec() { return babyAnalyzer.xsec(); }
	const float &xsec_uncert() { return babyAnalyzer.xsec_uncert(); }
	const float &kfactor() { return babyAnalyzer.kfactor(); }
	const float &pu_ntrue() { return babyAnalyzer.pu_ntrue(); }
	const int &ngoodleps() { return babyAnalyzer.ngoodleps(); }
	const int &nlooseleps() { return babyAnalyzer.nlooseleps(); }
	const int &nvetoleps() { return babyAnalyzer.nvetoleps(); }
	const bool &is_data() { return babyAnalyzer.is_data(); }
	const string &dataset() { return babyAnalyzer.dataset(); }
	const string &filename() { return babyAnalyzer.filename(); }
	const string &cms3tag() { return babyAnalyzer.cms3tag(); }
	const unsigned int &nEvents() { return babyAnalyzer.nEvents(); }
	const unsigned int &nEvents_goodvtx() { return babyAnalyzer.nEvents_goodvtx(); }
	const unsigned int &nEvents_MET30() { return babyAnalyzer.nEvents_MET30(); }
	const unsigned int &nEvents_1goodlep() { return babyAnalyzer.nEvents_1goodlep(); }
	const unsigned int &nEvents_2goodjets() { return babyAnalyzer.nEvents_2goodjets(); }
	const int &genlepsfromtop() { return babyAnalyzer.genlepsfromtop(); }
	const int &genLepsHardProcess() { return babyAnalyzer.genLepsHardProcess(); }
	const int &genNusHardProcess() { return babyAnalyzer.genNusHardProcess(); }
	const int &is0lep() { return babyAnalyzer.is0lep(); }
	const int &is1lep() { return babyAnalyzer.is1lep(); }
	const int &is2lep() { return babyAnalyzer.is2lep(); }
	const int &isZtoNuNu() { return babyAnalyzer.isZtoNuNu(); }
	const int &is1lepFromW() { return babyAnalyzer.is1lepFromW(); }
	const int &is1lepFromTop() { return babyAnalyzer.is1lepFromTop(); }
	const float &MT2W() { return babyAnalyzer.MT2W(); }
	const float &MT2W_lep2() { return babyAnalyzer.MT2W_lep2(); }
	const float &mindphi_met_j1_j2() { return babyAnalyzer.mindphi_met_j1_j2(); }
	const float &mt_met_lep() { return babyAnalyzer.mt_met_lep(); }
	const float &mt_met_lep2() { return babyAnalyzer.mt_met_lep2(); }
	const float &dR_lep_leadb() { return babyAnalyzer.dR_lep_leadb(); }
	const float &dR_lep2_leadb() { return babyAnalyzer.dR_lep2_leadb(); }
	const float &hadronic_top_chi2() { return babyAnalyzer.hadronic_top_chi2(); }
	const float &dphi_Wlep() { return babyAnalyzer.dphi_Wlep(); }
	const float &MET_over_sqrtHT() { return babyAnalyzer.MET_over_sqrtHT(); }
	const float &ak4pfjets_rho() { return babyAnalyzer.ak4pfjets_rho(); }
	const float &pdf_up_weight() { return babyAnalyzer.pdf_up_weight(); }
	const float &pdf_down_weight() { return babyAnalyzer.pdf_down_weight(); }
	const vector<string> &genweightsID() { return babyAnalyzer.genweightsID(); }
	const vector<float> &genweights() { return babyAnalyzer.genweights(); }
	const float &weight_btagsf() { return babyAnalyzer.weight_btagsf(); }
	const float &weight_btagsf_heavy_UP() { return babyAnalyzer.weight_btagsf_heavy_UP(); }
	const float &weight_btagsf_light_UP() { return babyAnalyzer.weight_btagsf_light_UP(); }
	const float &weight_btagsf_heavy_DN() { return babyAnalyzer.weight_btagsf_heavy_DN(); }
	const float &weight_btagsf_light_DN() { return babyAnalyzer.weight_btagsf_light_DN(); }
	const float &weight_ISR() { return babyAnalyzer.weight_ISR(); }
	const float &weight_ISRup() { return babyAnalyzer.weight_ISRup(); }
	const float &weight_ISRdown() { return babyAnalyzer.weight_ISRdown(); }
	const float &weight_PU() { return babyAnalyzer.weight_PU(); }
	const float &weight_PUup() { return babyAnalyzer.weight_PUup(); }
	const float &weight_PUdown() { return babyAnalyzer.weight_PUdown(); }
	const float &hardgenpt() { return babyAnalyzer.hardgenpt(); }
	const vector<string> &sparms_names() { return babyAnalyzer.sparms_names(); }
	const float &sparms_filterEfficiency() { return babyAnalyzer.sparms_filterEfficiency(); }
	const float &sparms_pdfScale() { return babyAnalyzer.sparms_pdfScale(); }
	const float &sparms_pdfWeight1() { return babyAnalyzer.sparms_pdfWeight1(); }
	const float &sparms_pdfWeight2() { return babyAnalyzer.sparms_pdfWeight2(); }
	const float &sparms_weight() { return babyAnalyzer.sparms_weight(); }
	const float &sparms_xsec() { return babyAnalyzer.sparms_xsec(); }
	const vector<float> &sparms_values() { return babyAnalyzer.sparms_values(); }
	const int &sparms_subProcessId() { return babyAnalyzer.sparms_subProcessId(); }
	const float &mass_lsp() { return babyAnalyzer.mass_lsp(); }
	const float &mass_chargino() { return babyAnalyzer.mass_chargino(); }
	const float &mass_stop() { return babyAnalyzer.mass_stop(); }
	const float &genmet() { return babyAnalyzer.genmet(); }
	const float &genmet_phi() { return babyAnalyzer.genmet_phi(); }
	const float &genht() { return babyAnalyzer.genht(); }
	const bool &PassTrackVeto() { return babyAnalyzer.PassTrackVeto(); }
	const bool &PassTrackVeto_v2() { return babyAnalyzer.PassTrackVeto_v2(); }
	const bool &PassTrackVeto_v3() { return babyAnalyzer.PassTrackVeto_v3(); }
	const bool &PassTauVeto() { return babyAnalyzer.PassTauVeto(); }
	const float &EA_all_rho() { return babyAnalyzer.EA_all_rho(); }
	const float &EA_allcalo_rho() { return babyAnalyzer.EA_allcalo_rho(); }
	const float &EA_centralcalo_rho() { return babyAnalyzer.EA_centralcalo_rho(); }
	const float &EA_centralchargedpileup_rho() { return babyAnalyzer.EA_centralchargedpileup_rho(); }
	const float &EA_centralneutral_rho() { return babyAnalyzer.EA_centralneutral_rho(); }
	const float &topness() { return babyAnalyzer.topness(); }
	const float &topness_lep2() { return babyAnalyzer.topness_lep2(); }
	const float &topnessMod() { return babyAnalyzer.topnessMod(); }
	const float &topnessMod_lep2() { return babyAnalyzer.topnessMod_lep2(); }
	const float &MT2_lb_b() { return babyAnalyzer.MT2_lb_b(); }
	const float &MT2_lb_b_lep2() { return babyAnalyzer.MT2_lb_b_lep2(); }
	const float &MT2_lb_b_mass() { return babyAnalyzer.MT2_lb_b_mass(); }
	const float &MT2_lb_b_mass_lep2() { return babyAnalyzer.MT2_lb_b_mass_lep2(); }
	const float &MT2_lb_bqq() { return babyAnalyzer.MT2_lb_bqq(); }
	const float &MT2_lb_bqq_lep2() { return babyAnalyzer.MT2_lb_bqq_lep2(); }
	const float &MT2_lb_bqq_mass() { return babyAnalyzer.MT2_lb_bqq_mass(); }
	const float &MT2_lb_bqq_mass_lep2() { return babyAnalyzer.MT2_lb_bqq_mass_lep2(); }
	const float &Mlb_closestb() { return babyAnalyzer.Mlb_closestb(); }
	const float &Mlb_lead_bdiscr() { return babyAnalyzer.Mlb_lead_bdiscr(); }
	const float &Mlb_closestb_lep2() { return babyAnalyzer.Mlb_closestb_lep2(); }
	const float &Mlb_lead_bdiscr_lep2() { return babyAnalyzer.Mlb_lead_bdiscr_lep2(); }
	const float &Mjjj() { return babyAnalyzer.Mjjj(); }
	const float &Mjjj_lep2() { return babyAnalyzer.Mjjj_lep2(); }
	const int &HLT_SingleEl() { return babyAnalyzer.HLT_SingleEl(); }
	const int &HLT_SingleMu() { return babyAnalyzer.HLT_SingleMu(); }
	const int &HLT_MET170() { return babyAnalyzer.HLT_MET170(); }
	const int &HLT_MET120Btag() { return babyAnalyzer.HLT_MET120Btag(); }
	const int &HLT_MET120Mu5() { return babyAnalyzer.HLT_MET120Mu5(); }
	const int &HLT_HT350MET120() { return babyAnalyzer.HLT_HT350MET120(); }
	const int &HLT_DiEl() { return babyAnalyzer.HLT_DiEl(); }
	const int &HLT_DiEl_17_12() { return babyAnalyzer.HLT_DiEl_17_12(); }
	const int &HLT_DiMu() { return babyAnalyzer.HLT_DiMu(); }
	const int &HLT_Mu8El17() { return babyAnalyzer.HLT_Mu8El17(); }
	const int &HLT_Mu8El23() { return babyAnalyzer.HLT_Mu8El23(); }
	const int &HLT_Mu17El12() { return babyAnalyzer.HLT_Mu17El12(); }
	const int &HLT_Mu23El12() { return babyAnalyzer.HLT_Mu23El12(); }
	const int &HLT_SingleEl23() { return babyAnalyzer.HLT_SingleEl23(); }
	const int &HLT_SingleEl27() { return babyAnalyzer.HLT_SingleEl27(); }
	const int &HLT_SingleEl27Tight() { return babyAnalyzer.HLT_SingleEl27Tight(); }
	const int &HLT_SingleElTight() { return babyAnalyzer.HLT_SingleElTight(); }
	const int &HLT_SingleElHT200() { return babyAnalyzer.HLT_SingleElHT200(); }
	const int &HLT_SingleMuNoEta() { return babyAnalyzer.HLT_SingleMuNoEta(); }
	const int &HLT_SingleMuNoIso() { return babyAnalyzer.HLT_SingleMuNoIso(); }
	const int &HLT_SingleMuNoIsoNoEta() { return babyAnalyzer.HLT_SingleMuNoIsoNoEta(); }
	const int &HLT_Mu6HT200MET100() { return babyAnalyzer.HLT_Mu6HT200MET100(); }
	const int &HLT_HT350MET100() { return babyAnalyzer.HLT_HT350MET100(); }
	const int &HLT_SingleMu17() { return babyAnalyzer.HLT_SingleMu17(); }
	const int &HLT_SingleMu18() { return babyAnalyzer.HLT_SingleMu18(); }
	const int &HLT_SingleMu20() { return babyAnalyzer.HLT_SingleMu20(); }
	const int &HLT_SingleMu24() { return babyAnalyzer.HLT_SingleMu24(); }
	const int &HLT_MonoCentPFJet80_METNoMu90_MHTNoMu90_IDTight() { return babyAnalyzer.HLT_MonoCentPFJet80_METNoMu90_MHTNoMu90_IDTight(); }
	const int &HLT_MET90_MHT90_IDTight() { return babyAnalyzer.HLT_MET90_MHT90_IDTight(); }
	const int &HLT_METNoMu90_NoiseCleaned_MHTNoMu90_IDTight() { return babyAnalyzer.HLT_METNoMu90_NoiseCleaned_MHTNoMu90_IDTight(); }
	const int &HLT_Photon90_CaloIdL_PFHT500() { return babyAnalyzer.HLT_Photon90_CaloIdL_PFHT500(); }
	const int &HLT_Photon22_R9Id90_HE10_IsoM() { return babyAnalyzer.HLT_Photon22_R9Id90_HE10_IsoM(); }
	const int &HLT_Photon30_R9Id90_HE10_IsoM() { return babyAnalyzer.HLT_Photon30_R9Id90_HE10_IsoM(); }
	const int &HLT_Photon36_R9Id90_HE10_IsoM() { return babyAnalyzer.HLT_Photon36_R9Id90_HE10_IsoM(); }
	const int &HLT_Photon50_R9Id90_HE10_IsoM() { return babyAnalyzer.HLT_Photon50_R9Id90_HE10_IsoM(); }
	const int &HLT_Photon75_R9Id90_HE10_IsoM() { return babyAnalyzer.HLT_Photon75_R9Id90_HE10_IsoM(); }
	const int &HLT_Photon90_R9Id90_HE10_IsoM() { return babyAnalyzer.HLT_Photon90_R9Id90_HE10_IsoM(); }
	const int &HLT_Photon120_R9Id90_HE10_IsoM() { return babyAnalyzer.HLT_Photon120_R9Id90_HE10_IsoM(); }
	const int &HLT_Photon165_R9Id90_HE10_IsoM() { return babyAnalyzer.HLT_Photon165_R9Id90_HE10_IsoM(); }
	const int &HLT_Photon175() { return babyAnalyzer.HLT_Photon175(); }
	const int &HLT_Photon165_HE10() { return babyAnalyzer.HLT_Photon165_HE10(); }
	const float &lep_sf() { return babyAnalyzer.lep_sf(); }
	const float &btag_sf() { return babyAnalyzer.btag_sf(); }
	const float &HLT_SingleEl_eff() { return babyAnalyzer.HLT_SingleEl_eff(); }
	const float &HLT_SingleMu_eff() { return babyAnalyzer.HLT_SingleMu_eff(); }
	const int &nPhotons() { return babyAnalyzer.nPhotons(); }
	const int &ph_selectedidx() { return babyAnalyzer.ph_selectedidx(); }
	const int &ph_ngoodjets() { return babyAnalyzer.ph_ngoodjets(); }
	const int &ph_ngoodbtags() { return babyAnalyzer.ph_ngoodbtags(); }
	const float &ph_met() { return babyAnalyzer.ph_met(); }
	const float &ph_met_phi() { return babyAnalyzer.ph_met_phi(); }
	const float &ph_HT() { return babyAnalyzer.ph_HT(); }
	const float &ph_htssm() { return babyAnalyzer.ph_htssm(); }
	const float &ph_htosm() { return babyAnalyzer.ph_htosm(); }
	const float &ph_htratiom() { return babyAnalyzer.ph_htratiom(); }
	const float &ph_mt_met_lep() { return babyAnalyzer.ph_mt_met_lep(); }
	const float &ph_dphi_Wlep() { return babyAnalyzer.ph_dphi_Wlep(); }
	const float &ph_MT2W() { return babyAnalyzer.ph_MT2W(); }
	const float &ph_topness() { return babyAnalyzer.ph_topness(); }
	const float &ph_topnessMod() { return babyAnalyzer.ph_topnessMod(); }
	const float &ph_MT2_lb_b_mass() { return babyAnalyzer.ph_MT2_lb_b_mass(); }
	const float &ph_MT2_lb_b() { return babyAnalyzer.ph_MT2_lb_b(); }
	const float &ph_MT2_lb_bqq_mass() { return babyAnalyzer.ph_MT2_lb_bqq_mass(); }
	const float &ph_MT2_lb_bqq() { return babyAnalyzer.ph_MT2_lb_bqq(); }
	const float &ph_hadronic_top_chi2() { return babyAnalyzer.ph_hadronic_top_chi2(); }
	const float &ph_mindphi_met_j1_j2() { return babyAnalyzer.ph_mindphi_met_j1_j2(); }
	const float &ph_Mlb_lead_bdiscr() { return babyAnalyzer.ph_Mlb_lead_bdiscr(); }
	const float &ph_dR_lep_leadb() { return babyAnalyzer.ph_dR_lep_leadb(); }
	const float &ph_Mlb_closestb() { return babyAnalyzer.ph_Mlb_closestb(); }
	const float &ph_Mjjj() { return babyAnalyzer.ph_Mjjj(); }
	const int &Zll_idl1() { return babyAnalyzer.Zll_idl1(); }
	const int &Zll_idl2() { return babyAnalyzer.Zll_idl2(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &Zll_p4l1() { return babyAnalyzer.Zll_p4l1(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &Zll_p4l2() { return babyAnalyzer.Zll_p4l2(); }
	const bool &Zll_OS() { return babyAnalyzer.Zll_OS(); }
	const bool &Zll_SF() { return babyAnalyzer.Zll_SF(); }
	const bool &Zll_isZmass() { return babyAnalyzer.Zll_isZmass(); }
	const float &Zll_M() { return babyAnalyzer.Zll_M(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &Zll_p4() { return babyAnalyzer.Zll_p4(); }
	const int &Zll_selLep() { return babyAnalyzer.Zll_selLep(); }
	const float &Zll_met() { return babyAnalyzer.Zll_met(); }
	const float &Zll_met_phi() { return babyAnalyzer.Zll_met_phi(); }
	const float &Zll_mindphi_met_j1_j2() { return babyAnalyzer.Zll_mindphi_met_j1_j2(); }
	const float &Zll_mt_met_lep() { return babyAnalyzer.Zll_mt_met_lep(); }
	const float &Zll_dphi_Wlep() { return babyAnalyzer.Zll_dphi_Wlep(); }
	const float &Zll_MT2W() { return babyAnalyzer.Zll_MT2W(); }
	const float &Zll_topness() { return babyAnalyzer.Zll_topness(); }
	const float &Zll_topnessMod() { return babyAnalyzer.Zll_topnessMod(); }
	const float &Zll_MT2_lb_b_mass() { return babyAnalyzer.Zll_MT2_lb_b_mass(); }
	const float &Zll_MT2_lb_b() { return babyAnalyzer.Zll_MT2_lb_b(); }
	const float &Zll_MT2_lb_bqq_mass() { return babyAnalyzer.Zll_MT2_lb_bqq_mass(); }
	const float &Zll_MT2_lb_bqq() { return babyAnalyzer.Zll_MT2_lb_bqq(); }
	const bool &lep1_is_mu() { return babyAnalyzer.lep1_is_mu(); }
	const bool &lep1_is_el() { return babyAnalyzer.lep1_is_el(); }
	const int &lep1_charge() { return babyAnalyzer.lep1_charge(); }
	const int &lep1_pdgid() { return babyAnalyzer.lep1_pdgid(); }
	const int &lep1_type() { return babyAnalyzer.lep1_type(); }
	const int &lep1_production_type() { return babyAnalyzer.lep1_production_type(); }
	const float &lep1_d0() { return babyAnalyzer.lep1_d0(); }
	const float &lep1_d0err() { return babyAnalyzer.lep1_d0err(); }
	const float &lep1_dz() { return babyAnalyzer.lep1_dz(); }
	const float &lep1_dzerr() { return babyAnalyzer.lep1_dzerr(); }
	const float &lep1_sigmaIEtaEta_fill5x5() { return babyAnalyzer.lep1_sigmaIEtaEta_fill5x5(); }
	const float &lep1_dEtaIn() { return babyAnalyzer.lep1_dEtaIn(); }
	const float &lep1_dPhiIn() { return babyAnalyzer.lep1_dPhiIn(); }
	const float &lep1_hOverE() { return babyAnalyzer.lep1_hOverE(); }
	const float &lep1_ooEmooP() { return babyAnalyzer.lep1_ooEmooP(); }
	const int &lep1_expectedMissingInnerHits() { return babyAnalyzer.lep1_expectedMissingInnerHits(); }
	const bool &lep1_conversionVeto() { return babyAnalyzer.lep1_conversionVeto(); }
	const float &lep1_etaSC() { return babyAnalyzer.lep1_etaSC(); }
	const float &lep1_ChiSqr() { return babyAnalyzer.lep1_ChiSqr(); }
	const float &lep1_chiso() { return babyAnalyzer.lep1_chiso(); }
	const float &lep1_nhiso() { return babyAnalyzer.lep1_nhiso(); }
	const float &lep1_emiso() { return babyAnalyzer.lep1_emiso(); }
	const float &lep1_deltaBeta() { return babyAnalyzer.lep1_deltaBeta(); }
	const float &lep1_relIso03DB() { return babyAnalyzer.lep1_relIso03DB(); }
	const float &lep1_relIso03EA() { return babyAnalyzer.lep1_relIso03EA(); }
	const float &lep1_relIso04DB() { return babyAnalyzer.lep1_relIso04DB(); }
	const float &lep1_miniRelIsoDB() { return babyAnalyzer.lep1_miniRelIsoDB(); }
	const float &lep1_miniRelIsoEA() { return babyAnalyzer.lep1_miniRelIsoEA(); }
	const float &lep1_MiniIso() { return babyAnalyzer.lep1_MiniIso(); }
	const int &lep1_mcid() { return babyAnalyzer.lep1_mcid(); }
	const int &lep1_mcstatus() { return babyAnalyzer.lep1_mcstatus(); }
	const int &lep1_mc3dr() { return babyAnalyzer.lep1_mc3dr(); }
	const int &lep1_mc3id() { return babyAnalyzer.lep1_mc3id(); }
	const int &lep1_mc3idx() { return babyAnalyzer.lep1_mc3idx(); }
	const int &lep1_mc3motherid() { return babyAnalyzer.lep1_mc3motherid(); }
	const int &lep1_mc3motheridx() { return babyAnalyzer.lep1_mc3motheridx(); }
	const bool &lep1_is_eleid_loose() { return babyAnalyzer.lep1_is_eleid_loose(); }
	const bool &lep1_is_eleid_medium() { return babyAnalyzer.lep1_is_eleid_medium(); }
	const bool &lep1_is_eleid_tight() { return babyAnalyzer.lep1_is_eleid_tight(); }
	const bool &lep1_is_phys14_loose_noIso() { return babyAnalyzer.lep1_is_phys14_loose_noIso(); }
	const bool &lep1_is_phys14_medium_noIso() { return babyAnalyzer.lep1_is_phys14_medium_noIso(); }
	const bool &lep1_is_phys14_tight_noIso() { return babyAnalyzer.lep1_is_phys14_tight_noIso(); }
	const float &lep1_eoverpin() { return babyAnalyzer.lep1_eoverpin(); }
	const bool &lep1_is_muoid_loose() { return babyAnalyzer.lep1_is_muoid_loose(); }
	const bool &lep1_is_muoid_medium() { return babyAnalyzer.lep1_is_muoid_medium(); }
	const bool &lep1_is_muoid_tight() { return babyAnalyzer.lep1_is_muoid_tight(); }
	const float &lep1_ip3d() { return babyAnalyzer.lep1_ip3d(); }
	const float &lep1_ip3derr() { return babyAnalyzer.lep1_ip3derr(); }
	const bool &lep1_is_pfmu() { return babyAnalyzer.lep1_is_pfmu(); }
	const bool &lep1_passMediumID() { return babyAnalyzer.lep1_passMediumID(); }
	const bool &lep1_passVeto() { return babyAnalyzer.lep1_passVeto(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &lep1_p4() { return babyAnalyzer.lep1_p4(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &lep1_mcp4() { return babyAnalyzer.lep1_mcp4(); }
	const float &lep1_pt() { return babyAnalyzer.lep1_pt(); }
	const float &lep1_eta() { return babyAnalyzer.lep1_eta(); }
	const float &lep1_phi() { return babyAnalyzer.lep1_phi(); }
	const float &lep1_mass() { return babyAnalyzer.lep1_mass(); }
	const bool &lep2_is_mu() { return babyAnalyzer.lep2_is_mu(); }
	const bool &lep2_is_el() { return babyAnalyzer.lep2_is_el(); }
	const int &lep2_charge() { return babyAnalyzer.lep2_charge(); }
	const int &lep2_pdgid() { return babyAnalyzer.lep2_pdgid(); }
	const int &lep2_type() { return babyAnalyzer.lep2_type(); }
	const int &lep2_production_type() { return babyAnalyzer.lep2_production_type(); }
	const float &lep2_d0() { return babyAnalyzer.lep2_d0(); }
	const float &lep2_d0err() { return babyAnalyzer.lep2_d0err(); }
	const float &lep2_dz() { return babyAnalyzer.lep2_dz(); }
	const float &lep2_dzerr() { return babyAnalyzer.lep2_dzerr(); }
	const float &lep2_sigmaIEtaEta_fill5x5() { return babyAnalyzer.lep2_sigmaIEtaEta_fill5x5(); }
	const float &lep2_dEtaIn() { return babyAnalyzer.lep2_dEtaIn(); }
	const float &lep2_dPhiIn() { return babyAnalyzer.lep2_dPhiIn(); }
	const float &lep2_hOverE() { return babyAnalyzer.lep2_hOverE(); }
	const float &lep2_ooEmooP() { return babyAnalyzer.lep2_ooEmooP(); }
	const int &lep2_expectedMissingInnerHits() { return babyAnalyzer.lep2_expectedMissingInnerHits(); }
	const bool &lep2_conversionVeto() { return babyAnalyzer.lep2_conversionVeto(); }
	const float &lep2_etaSC() { return babyAnalyzer.lep2_etaSC(); }
	const float &lep2_ChiSqr() { return babyAnalyzer.lep2_ChiSqr(); }
	const float &lep2_chiso() { return babyAnalyzer.lep2_chiso(); }
	const float &lep2_nhiso() { return babyAnalyzer.lep2_nhiso(); }
	const float &lep2_emiso() { return babyAnalyzer.lep2_emiso(); }
	const float &lep2_deltaBeta() { return babyAnalyzer.lep2_deltaBeta(); }
	const float &lep2_relIso03DB() { return babyAnalyzer.lep2_relIso03DB(); }
	const float &lep2_relIso03EA() { return babyAnalyzer.lep2_relIso03EA(); }
	const float &lep2_relIso04DB() { return babyAnalyzer.lep2_relIso04DB(); }
	const float &lep2_miniRelIsoDB() { return babyAnalyzer.lep2_miniRelIsoDB(); }
	const float &lep2_miniRelIsoEA() { return babyAnalyzer.lep2_miniRelIsoEA(); }
	const float &lep2_MiniIso() { return babyAnalyzer.lep2_MiniIso(); }
	const int &lep2_mcid() { return babyAnalyzer.lep2_mcid(); }
	const int &lep2_mcstatus() { return babyAnalyzer.lep2_mcstatus(); }
	const int &lep2_mc3dr() { return babyAnalyzer.lep2_mc3dr(); }
	const int &lep2_mc3id() { return babyAnalyzer.lep2_mc3id(); }
	const int &lep2_mc3idx() { return babyAnalyzer.lep2_mc3idx(); }
	const int &lep2_mc3motherid() { return babyAnalyzer.lep2_mc3motherid(); }
	const int &lep2_mc3motheridx() { return babyAnalyzer.lep2_mc3motheridx(); }
	const bool &lep2_is_eleid_loose() { return babyAnalyzer.lep2_is_eleid_loose(); }
	const bool &lep2_is_eleid_medium() { return babyAnalyzer.lep2_is_eleid_medium(); }
	const bool &lep2_is_eleid_tight() { return babyAnalyzer.lep2_is_eleid_tight(); }
	const bool &lep2_is_phys14_loose_noIso() { return babyAnalyzer.lep2_is_phys14_loose_noIso(); }
	const bool &lep2_is_phys14_medium_noIso() { return babyAnalyzer.lep2_is_phys14_medium_noIso(); }
	const bool &lep2_is_phys14_tight_noIso() { return babyAnalyzer.lep2_is_phys14_tight_noIso(); }
	const float &lep2_eoverpin() { return babyAnalyzer.lep2_eoverpin(); }
	const bool &lep2_is_muoid_loose() { return babyAnalyzer.lep2_is_muoid_loose(); }
	const bool &lep2_is_muoid_medium() { return babyAnalyzer.lep2_is_muoid_medium(); }
	const bool &lep2_is_muoid_tight() { return babyAnalyzer.lep2_is_muoid_tight(); }
	const float &lep2_ip3d() { return babyAnalyzer.lep2_ip3d(); }
	const float &lep2_ip3derr() { return babyAnalyzer.lep2_ip3derr(); }
	const bool &lep2_is_pfmu() { return babyAnalyzer.lep2_is_pfmu(); }
	const bool &lep2_passMediumID() { return babyAnalyzer.lep2_passMediumID(); }
	const bool &lep2_passVeto() { return babyAnalyzer.lep2_passVeto(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &lep2_p4() { return babyAnalyzer.lep2_p4(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &lep2_mcp4() { return babyAnalyzer.lep2_mcp4(); }
	const float &lep2_pt() { return babyAnalyzer.lep2_pt(); }
	const float &lep2_eta() { return babyAnalyzer.lep2_eta(); }
	const float &lep2_phi() { return babyAnalyzer.lep2_phi(); }
	const float &lep2_mass() { return babyAnalyzer.lep2_mass(); }
	const vector<float> &ph_sigmaIEtaEta_fill5x5() { return babyAnalyzer.ph_sigmaIEtaEta_fill5x5(); }
	const vector<float> &ph_hOverE() { return babyAnalyzer.ph_hOverE(); }
	const vector<float> &ph_r9() { return babyAnalyzer.ph_r9(); }
	const vector<float> &ph_chiso() { return babyAnalyzer.ph_chiso(); }
	const vector<float> &ph_nhiso() { return babyAnalyzer.ph_nhiso(); }
	const vector<float> &ph_phiso() { return babyAnalyzer.ph_phiso(); }
	const vector<bool> &ph_idCutBased() { return babyAnalyzer.ph_idCutBased(); }
	const vector<int> &ph_overlapJetId() { return babyAnalyzer.ph_overlapJetId(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &ph_p4() { return babyAnalyzer.ph_p4(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &ph_mcp4() { return babyAnalyzer.ph_mcp4(); }
	const vector<float> &ph_pt() { return babyAnalyzer.ph_pt(); }
	const vector<float> &ph_eta() { return babyAnalyzer.ph_eta(); }
	const vector<float> &ph_phi() { return babyAnalyzer.ph_phi(); }
	const vector<float> &ph_mass() { return babyAnalyzer.ph_mass(); }
	const vector<int> &ph_mcMatchId() { return babyAnalyzer.ph_mcMatchId(); }
	const vector<float> &ph_genIso04() { return babyAnalyzer.ph_genIso04(); }
	const vector<float> &ph_drMinParton() { return babyAnalyzer.ph_drMinParton(); }
	const int &nGoodGenJets() { return babyAnalyzer.nGoodGenJets(); }
	const int &ngoodjets() { return babyAnalyzer.ngoodjets(); }
	const int &nfailjets() { return babyAnalyzer.nfailjets(); }
	const int &ak8GoodPFJets() { return babyAnalyzer.ak8GoodPFJets(); }
	const int &ngoodbtags() { return babyAnalyzer.ngoodbtags(); }
	const float &ak4_HT() { return babyAnalyzer.ak4_HT(); }
	const float &ak4_htssm() { return babyAnalyzer.ak4_htssm(); }
	const float &ak4_htosm() { return babyAnalyzer.ak4_htosm(); }
	const float &ak4_htratiom() { return babyAnalyzer.ak4_htratiom(); }
	const vector<float> &dphi_ak4pfjet_met() { return babyAnalyzer.dphi_ak4pfjet_met(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &ak4pfjets_p4() { return babyAnalyzer.ak4pfjets_p4(); }
	const vector<float> &ak4pfjets_pt() { return babyAnalyzer.ak4pfjets_pt(); }
	const vector<float> &ak4pfjets_eta() { return babyAnalyzer.ak4pfjets_eta(); }
	const vector<float> &ak4pfjets_phi() { return babyAnalyzer.ak4pfjets_phi(); }
	const vector<float> &ak4pfjets_mass() { return babyAnalyzer.ak4pfjets_mass(); }
	const vector<bool> &ak4pfjets_passMEDbtag() { return babyAnalyzer.ak4pfjets_passMEDbtag(); }
	const vector<float> &ak4pfjets_qg_disc() { return babyAnalyzer.ak4pfjets_qg_disc(); }
	const vector<float> &ak4pfjets_CSV() { return babyAnalyzer.ak4pfjets_CSV(); }
	const vector<float> &ak4pfjets_puid() { return babyAnalyzer.ak4pfjets_puid(); }
	const vector<int> &ak4pfjets_parton_flavor() { return babyAnalyzer.ak4pfjets_parton_flavor(); }
	const vector<int> &ak4pfjets_hadron_flavor() { return babyAnalyzer.ak4pfjets_hadron_flavor(); }
	const vector<bool> &ak4pfjets_loose_puid() { return babyAnalyzer.ak4pfjets_loose_puid(); }
	const vector<bool> &ak4pfjets_loose_pfid() { return babyAnalyzer.ak4pfjets_loose_pfid(); }
	const vector<bool> &ak4pfjets_medium_pfid() { return babyAnalyzer.ak4pfjets_medium_pfid(); }
	const vector<bool> &ak4pfjets_tight_pfid() { return babyAnalyzer.ak4pfjets_tight_pfid(); }
	const vector<float> &ak4pfjets_MEDbjet_pt() { return babyAnalyzer.ak4pfjets_MEDbjet_pt(); }
	const float &ak4pfjets_leadMEDbjet_pt() { return babyAnalyzer.ak4pfjets_leadMEDbjet_pt(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &ak4pfjets_leadMEDbjet_p4() { return babyAnalyzer.ak4pfjets_leadMEDbjet_p4(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &ak4pfjets_leadbtag_p4() { return babyAnalyzer.ak4pfjets_leadbtag_p4(); }
	const vector<float> &ak4pfjets_chf() { return babyAnalyzer.ak4pfjets_chf(); }
	const vector<float> &ak4pfjets_nhf() { return babyAnalyzer.ak4pfjets_nhf(); }
	const vector<float> &ak4pfjets_cef() { return babyAnalyzer.ak4pfjets_cef(); }
	const vector<float> &ak4pfjets_nef() { return babyAnalyzer.ak4pfjets_nef(); }
	const vector<float> &ak4pfjets_muf() { return babyAnalyzer.ak4pfjets_muf(); }
	const vector<int> &ak4pfjets_cm() { return babyAnalyzer.ak4pfjets_cm(); }
	const vector<int> &ak4pfjets_nm() { return babyAnalyzer.ak4pfjets_nm(); }
	const vector<int> &ak4pfjets_mc3dr() { return babyAnalyzer.ak4pfjets_mc3dr(); }
	const vector<int> &ak4pfjets_mc3id() { return babyAnalyzer.ak4pfjets_mc3id(); }
	const vector<int> &ak4pfjets_mc3idx() { return babyAnalyzer.ak4pfjets_mc3idx(); }
	const vector<int> &ak4pfjets_mcmotherid() { return babyAnalyzer.ak4pfjets_mcmotherid(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &ak4pfjet_overlep1_p4() { return babyAnalyzer.ak4pfjet_overlep1_p4(); }
	const float &ak4pfjet_overlep1_CSV() { return babyAnalyzer.ak4pfjet_overlep1_CSV(); }
	const float &ak4pfjet_overlep1_pu_id() { return babyAnalyzer.ak4pfjet_overlep1_pu_id(); }
	const float &ak4pfjet_overlep1_chf() { return babyAnalyzer.ak4pfjet_overlep1_chf(); }
	const float &ak4pfjet_overlep1_nhf() { return babyAnalyzer.ak4pfjet_overlep1_nhf(); }
	const float &ak4pfjet_overlep1_cef() { return babyAnalyzer.ak4pfjet_overlep1_cef(); }
	const float &ak4pfjet_overlep1_nef() { return babyAnalyzer.ak4pfjet_overlep1_nef(); }
	const float &ak4pfjet_overlep1_muf() { return babyAnalyzer.ak4pfjet_overlep1_muf(); }
	const int &ak4pfjet_overlep1_cm() { return babyAnalyzer.ak4pfjet_overlep1_cm(); }
	const int &ak4pfjet_overlep1_nm() { return babyAnalyzer.ak4pfjet_overlep1_nm(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &ak4pfjet_overlep2_p4() { return babyAnalyzer.ak4pfjet_overlep2_p4(); }
	const float &ak4pfjet_overlep2_CSV() { return babyAnalyzer.ak4pfjet_overlep2_CSV(); }
	const float &ak4pfjet_overlep2_pu_id() { return babyAnalyzer.ak4pfjet_overlep2_pu_id(); }
	const float &ak4pfjet_overlep2_chf() { return babyAnalyzer.ak4pfjet_overlep2_chf(); }
	const float &ak4pfjet_overlep2_nhf() { return babyAnalyzer.ak4pfjet_overlep2_nhf(); }
	const float &ak4pfjet_overlep2_cef() { return babyAnalyzer.ak4pfjet_overlep2_cef(); }
	const float &ak4pfjet_overlep2_nef() { return babyAnalyzer.ak4pfjet_overlep2_nef(); }
	const float &ak4pfjet_overlep2_muf() { return babyAnalyzer.ak4pfjet_overlep2_muf(); }
	const int &ak4pfjet_overlep2_cm() { return babyAnalyzer.ak4pfjet_overlep2_cm(); }
	const int &ak4pfjet_overlep2_nm() { return babyAnalyzer.ak4pfjet_overlep2_nm(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &ak8pfjets_p4() { return babyAnalyzer.ak8pfjets_p4(); }
	const vector<float> &ak8pfjets_tau1() { return babyAnalyzer.ak8pfjets_tau1(); }
	const vector<float> &ak8pfjets_tau2() { return babyAnalyzer.ak8pfjets_tau2(); }
	const vector<float> &ak8pfjets_tau3() { return babyAnalyzer.ak8pfjets_tau3(); }
	const vector<float> &ak8pfjets_top_mass() { return babyAnalyzer.ak8pfjets_top_mass(); }
	const vector<float> &ak8pfjets_pruned_mass() { return babyAnalyzer.ak8pfjets_pruned_mass(); }
	const vector<float> &ak8pfjets_trimmed_mass() { return babyAnalyzer.ak8pfjets_trimmed_mass(); }
	const vector<float> &ak8pfjets_filtered_mass() { return babyAnalyzer.ak8pfjets_filtered_mass(); }
	const vector<float> &ak8pfjets_pu_id() { return babyAnalyzer.ak8pfjets_pu_id(); }
	const vector<int> &ak8pfjets_parton_flavor() { return babyAnalyzer.ak8pfjets_parton_flavor(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &ak4genjets_p4() { return babyAnalyzer.ak4genjets_p4(); }
	const vector<TString> &tau_IDnames() { return babyAnalyzer.tau_IDnames(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &tau_leadtrack_p4() { return babyAnalyzer.tau_leadtrack_p4(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &tau_leadneutral_p4() { return babyAnalyzer.tau_leadneutral_p4(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &tau_p4() { return babyAnalyzer.tau_p4(); }
	const vector<vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > > &tau_isocand_p4() { return babyAnalyzer.tau_isocand_p4(); }
	const vector<vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > > &tau_sigcand_p4() { return babyAnalyzer.tau_sigcand_p4(); }
	const vector<float> &tau_mass() { return babyAnalyzer.tau_mass(); }
	const vector<vector<float> > &tau_ID() { return babyAnalyzer.tau_ID(); }
	const vector<float> &tau_passID() { return babyAnalyzer.tau_passID(); }
	const vector<float> &tau_charge() { return babyAnalyzer.tau_charge(); }
	const int &ngoodtaus() { return babyAnalyzer.ngoodtaus(); }
	const vector<float> &tau_againstMuonTight() { return babyAnalyzer.tau_againstMuonTight(); }
	const vector<float> &tau_againstElectronLoose() { return babyAnalyzer.tau_againstElectronLoose(); }
	const vector<bool> &tau_isVetoTau() { return babyAnalyzer.tau_isVetoTau(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &isoTracks_p4() { return babyAnalyzer.isoTracks_p4(); }
	const vector<int> &isoTracks_charge() { return babyAnalyzer.isoTracks_charge(); }
	const vector<float> &isoTracks_absIso() { return babyAnalyzer.isoTracks_absIso(); }
	const vector<float> &isoTracks_dz() { return babyAnalyzer.isoTracks_dz(); }
	const vector<int> &isoTracks_pdgId() { return babyAnalyzer.isoTracks_pdgId(); }
	const vector<int> &isoTracks_selectedidx() { return babyAnalyzer.isoTracks_selectedidx(); }
	const int &isoTracks_nselected() { return babyAnalyzer.isoTracks_nselected(); }
	const vector<bool> &isoTracks_isVetoTrack() { return babyAnalyzer.isoTracks_isVetoTrack(); }
	const vector<bool> &isoTracks_isVetoTrack_v2() { return babyAnalyzer.isoTracks_isVetoTrack_v2(); }
	const vector<bool> &isoTracks_isVetoTrack_v3() { return babyAnalyzer.isoTracks_isVetoTrack_v3(); }
	const vector<bool> &genleps_isfromt() { return babyAnalyzer.genleps_isfromt(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &genleps_p4() { return babyAnalyzer.genleps_p4(); }
	const vector<int> &genleps_id() { return babyAnalyzer.genleps_id(); }
	const vector<int> &genleps__genpsidx() { return babyAnalyzer.genleps__genpsidx(); }
	const vector<int> &genleps_status() { return babyAnalyzer.genleps_status(); }
	const vector<bool> &genleps_fromHardProcessDecayed() { return babyAnalyzer.genleps_fromHardProcessDecayed(); }
	const vector<bool> &genleps_fromHardProcessFinalState() { return babyAnalyzer.genleps_fromHardProcessFinalState(); }
	const vector<bool> &genleps_isHardProcess() { return babyAnalyzer.genleps_isHardProcess(); }
	const vector<bool> &genleps_isLastCopy() { return babyAnalyzer.genleps_isLastCopy(); }
	const vector<int> &genleps_gentaudecay() { return babyAnalyzer.genleps_gentaudecay(); }
	const int &gen_nfromtleps_() { return babyAnalyzer.gen_nfromtleps_(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &genleps_motherp4() { return babyAnalyzer.genleps_motherp4(); }
	const vector<int> &genleps_motherid() { return babyAnalyzer.genleps_motherid(); }
	const vector<int> &genleps_motheridx() { return babyAnalyzer.genleps_motheridx(); }
	const vector<int> &genleps_motherstatus() { return babyAnalyzer.genleps_motherstatus(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &genleps_gmotherp4() { return babyAnalyzer.genleps_gmotherp4(); }
	const vector<int> &genleps_gmotherid() { return babyAnalyzer.genleps_gmotherid(); }
	const vector<int> &genleps_gmotheridx() { return babyAnalyzer.genleps_gmotheridx(); }
	const vector<int> &genleps_gmotherstatus() { return babyAnalyzer.genleps_gmotherstatus(); }
	const vector<bool> &gennus_isfromt() { return babyAnalyzer.gennus_isfromt(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &gennus_p4() { return babyAnalyzer.gennus_p4(); }
	const vector<int> &gennus_id() { return babyAnalyzer.gennus_id(); }
	const vector<int> &gennus__genpsidx() { return babyAnalyzer.gennus__genpsidx(); }
	const vector<int> &gennus_status() { return babyAnalyzer.gennus_status(); }
	const vector<bool> &gennus_fromHardProcessDecayed() { return babyAnalyzer.gennus_fromHardProcessDecayed(); }
	const vector<bool> &gennus_fromHardProcessFinalState() { return babyAnalyzer.gennus_fromHardProcessFinalState(); }
	const vector<bool> &gennus_isHardProcess() { return babyAnalyzer.gennus_isHardProcess(); }
	const vector<bool> &gennus_isLastCopy() { return babyAnalyzer.gennus_isLastCopy(); }
	const vector<int> &gennus_gentaudecay() { return babyAnalyzer.gennus_gentaudecay(); }
	const int &gen_nfromtnus_() { return babyAnalyzer.gen_nfromtnus_(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &gennus_motherp4() { return babyAnalyzer.gennus_motherp4(); }
	const vector<int> &gennus_motherid() { return babyAnalyzer.gennus_motherid(); }
	const vector<int> &gennus_motheridx() { return babyAnalyzer.gennus_motheridx(); }
	const vector<int> &gennus_motherstatus() { return babyAnalyzer.gennus_motherstatus(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &gennus_gmotherp4() { return babyAnalyzer.gennus_gmotherp4(); }
	const vector<int> &gennus_gmotherid() { return babyAnalyzer.gennus_gmotherid(); }
	const vector<int> &gennus_gmotheridx() { return babyAnalyzer.gennus_gmotheridx(); }
	const vector<int> &gennus_gmotherstatus() { return babyAnalyzer.gennus_gmotherstatus(); }
	const vector<bool> &gents_isfromt() { return babyAnalyzer.gents_isfromt(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &gents_p4() { return babyAnalyzer.gents_p4(); }
	const vector<int> &gents_id() { return babyAnalyzer.gents_id(); }
	const vector<int> &gents__genpsidx() { return babyAnalyzer.gents__genpsidx(); }
	const vector<int> &gents_status() { return babyAnalyzer.gents_status(); }
	const vector<bool> &gents_fromHardProcessDecayed() { return babyAnalyzer.gents_fromHardProcessDecayed(); }
	const vector<bool> &gents_fromHardProcessFinalState() { return babyAnalyzer.gents_fromHardProcessFinalState(); }
	const vector<bool> &gents_isHardProcess() { return babyAnalyzer.gents_isHardProcess(); }
	const vector<bool> &gents_isLastCopy() { return babyAnalyzer.gents_isLastCopy(); }
	const vector<int> &gents_gentaudecay() { return babyAnalyzer.gents_gentaudecay(); }
	const int &gen_nfromtts_() { return babyAnalyzer.gen_nfromtts_(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &gents_motherp4() { return babyAnalyzer.gents_motherp4(); }
	const vector<int> &gents_motherid() { return babyAnalyzer.gents_motherid(); }
	const vector<int> &gents_motheridx() { return babyAnalyzer.gents_motheridx(); }
	const vector<int> &gents_motherstatus() { return babyAnalyzer.gents_motherstatus(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &gents_gmotherp4() { return babyAnalyzer.gents_gmotherp4(); }
	const vector<int> &gents_gmotherid() { return babyAnalyzer.gents_gmotherid(); }
	const vector<int> &gents_gmotheridx() { return babyAnalyzer.gents_gmotheridx(); }
	const vector<int> &gents_gmotherstatus() { return babyAnalyzer.gents_gmotherstatus(); }
	const vector<bool> &genqs_isfromt() { return babyAnalyzer.genqs_isfromt(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &genqs_p4() { return babyAnalyzer.genqs_p4(); }
	const vector<int> &genqs_id() { return babyAnalyzer.genqs_id(); }
	const vector<int> &genqs__genpsidx() { return babyAnalyzer.genqs__genpsidx(); }
	const vector<int> &genqs_status() { return babyAnalyzer.genqs_status(); }
	const vector<bool> &genqs_fromHardProcessDecayed() { return babyAnalyzer.genqs_fromHardProcessDecayed(); }
	const vector<bool> &genqs_fromHardProcessFinalState() { return babyAnalyzer.genqs_fromHardProcessFinalState(); }
	const vector<bool> &genqs_isHardProcess() { return babyAnalyzer.genqs_isHardProcess(); }
	const vector<bool> &genqs_isLastCopy() { return babyAnalyzer.genqs_isLastCopy(); }
	const vector<int> &genqs_gentaudecay() { return babyAnalyzer.genqs_gentaudecay(); }
	const int &gen_nfromtqs_() { return babyAnalyzer.gen_nfromtqs_(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &genqs_motherp4() { return babyAnalyzer.genqs_motherp4(); }
	const vector<int> &genqs_motherid() { return babyAnalyzer.genqs_motherid(); }
	const vector<int> &genqs_motheridx() { return babyAnalyzer.genqs_motheridx(); }
	const vector<int> &genqs_motherstatus() { return babyAnalyzer.genqs_motherstatus(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &genqs_gmotherp4() { return babyAnalyzer.genqs_gmotherp4(); }
	const vector<int> &genqs_gmotherid() { return babyAnalyzer.genqs_gmotherid(); }
	const vector<int> &genqs_gmotheridx() { return babyAnalyzer.genqs_gmotheridx(); }
	const vector<int> &genqs_gmotherstatus() { return babyAnalyzer.genqs_gmotherstatus(); }
	const vector<bool> &genbosons_isfromt() { return babyAnalyzer.genbosons_isfromt(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &genbosons_p4() { return babyAnalyzer.genbosons_p4(); }
	const vector<int> &genbosons_id() { return babyAnalyzer.genbosons_id(); }
	const vector<int> &genbosons__genpsidx() { return babyAnalyzer.genbosons__genpsidx(); }
	const vector<int> &genbosons_status() { return babyAnalyzer.genbosons_status(); }
	const vector<bool> &genbosons_fromHardProcessDecayed() { return babyAnalyzer.genbosons_fromHardProcessDecayed(); }
	const vector<bool> &genbosons_fromHardProcessFinalState() { return babyAnalyzer.genbosons_fromHardProcessFinalState(); }
	const vector<bool> &genbosons_isHardProcess() { return babyAnalyzer.genbosons_isHardProcess(); }
	const vector<bool> &genbosons_isLastCopy() { return babyAnalyzer.genbosons_isLastCopy(); }
	const vector<int> &genbosons_gentaudecay() { return babyAnalyzer.genbosons_gentaudecay(); }
	const int &gen_nfromtbosons_() { return babyAnalyzer.gen_nfromtbosons_(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &genbosons_motherp4() { return babyAnalyzer.genbosons_motherp4(); }
	const vector<int> &genbosons_motherid() { return babyAnalyzer.genbosons_motherid(); }
	const vector<int> &genbosons_motheridx() { return babyAnalyzer.genbosons_motheridx(); }
	const vector<int> &genbosons_motherstatus() { return babyAnalyzer.genbosons_motherstatus(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &genbosons_gmotherp4() { return babyAnalyzer.genbosons_gmotherp4(); }
	const vector<int> &genbosons_gmotherid() { return babyAnalyzer.genbosons_gmotherid(); }
	const vector<int> &genbosons_gmotheridx() { return babyAnalyzer.genbosons_gmotheridx(); }
	const vector<int> &genbosons_gmotherstatus() { return babyAnalyzer.genbosons_gmotherstatus(); }
	const vector<bool> &gensusy_isfromt() { return babyAnalyzer.gensusy_isfromt(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &gensusy_p4() { return babyAnalyzer.gensusy_p4(); }
	const vector<int> &gensusy_id() { return babyAnalyzer.gensusy_id(); }
	const vector<int> &gensusy__genpsidx() { return babyAnalyzer.gensusy__genpsidx(); }
	const vector<int> &gensusy_status() { return babyAnalyzer.gensusy_status(); }
	const vector<bool> &gensusy_fromHardProcessDecayed() { return babyAnalyzer.gensusy_fromHardProcessDecayed(); }
	const vector<bool> &gensusy_fromHardProcessFinalState() { return babyAnalyzer.gensusy_fromHardProcessFinalState(); }
	const vector<bool> &gensusy_isHardProcess() { return babyAnalyzer.gensusy_isHardProcess(); }
	const vector<bool> &gensusy_isLastCopy() { return babyAnalyzer.gensusy_isLastCopy(); }
	const vector<int> &gensusy_gentaudecay() { return babyAnalyzer.gensusy_gentaudecay(); }
	const int &gen_nfromtsusy_() { return babyAnalyzer.gen_nfromtsusy_(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &gensusy_motherp4() { return babyAnalyzer.gensusy_motherp4(); }
	const vector<int> &gensusy_motherid() { return babyAnalyzer.gensusy_motherid(); }
	const vector<int> &gensusy_motheridx() { return babyAnalyzer.gensusy_motheridx(); }
	const vector<int> &gensusy_motherstatus() { return babyAnalyzer.gensusy_motherstatus(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &gensusy_gmotherp4() { return babyAnalyzer.gensusy_gmotherp4(); }
	const vector<int> &gensusy_gmotherid() { return babyAnalyzer.gensusy_gmotherid(); }
	const vector<int> &gensusy_gmotheridx() { return babyAnalyzer.gensusy_gmotheridx(); }
	const vector<int> &gensusy_gmotherstatus() { return babyAnalyzer.gensusy_gmotherstatus(); }
}
