#!/bin/bash
############################
# Compile the latex to pdf #
############################
eval `../../tdr runtime -sh` 
# With line numbers
tdr --draft --style=an b AN-15-109
# Without line numbers
#tdr --nodraft --style=an b AN-15-109
exit


